### ISSUE TITLE
Market feed streaming not working

### ISSUE THREAD

**Issue by anurag-py** [OpenApi-5p/py5paisa#237]
* 5paisa Python SDK version: 0.7.0
* Python version: 3.10
* Operating System: Manjaro Linux

### Description

Trying to start streaming market feed for 3 scrips.
All the commands went through but neither any error was received nor the streaming started.

### What I Did

```
req_list = [{'Exch': 'N', 'ExchType': 'C', 'ScripCode': 999920005},
 {'Exch': 'N', 'ExchType': 'D', 'ScripCode': 39894},
 {'Exch': 'N', 'ExchType': 'D', 'ScripCode': 39875},]

req_data = client.Request_Feed('mf', 's', req_list)

def on_message(ws, message):
    # data = json.loads(message)
    print(message)


print(req_data)
res = client.connect(req_data)
print(res)
client.receive_data(on_message)

Output:: 

{'Method': 'MarketFeedV3', 'Operation': 'Subscribe', 'ClientCode': 'XXXXXXX', 'MarketFeedData': [{'Exch': 'N', 'ExchType': 'C', 'ScripCode': 999920005}, {'Exch': 'N', 'ExchType': 'D', 'ScripCode': 39894}, {'Exch': 'N', 'ExchType': 'D', 'ScripCode': 39875}]}
None

```

**Comment by 5paisa** [comment]
[{"Exch":"N","ExchType":"C","Token":999920005,"LastRate":43903.7,"LastQty":0,"TotalQty":0,"High":44144.15,"Low":43815.7,"OpenRate":44144.15,"PClose":44072.1,"AvgRate":0,"Time":39074,"BidQty":0,"BidRate":0,"OffQty":0,"OffRate":0,"TBidQ":0,"TOffQ":0,"TickDt":"\/Date(1684236074000)\/","ChgPcnt":0}]
[{"Exch":"N","ExchType":"D","Token":39894,"LastRate":0,"LastQty":0,"TotalQty":0,"High":0,"Low":0,"OpenRate":0,"PClose":0,"AvgRate":0,"Time":0,"BidQty":0,"BidRate":0,"OffQty":0,"OffRate":0,"TBidQ":0,"TOffQ":0,"TickDt":"\/Date(-62135596800000)\/","ChgPcnt":0}]
[{"Exch":"N","ExchType":"D","Token":39875,"LastRate":0,"LastQty":0,"TotalQty":0,"High":0,"Low":0,"OpenRate":0,"PClose":0,"AvgRate":0,"Time":0,"BidQty":0,"BidRate":0,"OffQty":0,"OffRate":0,"TBidQ":0,"TOffQ":0,"TickDt":"\/Date(-62135596800000)\/","ChgPcnt":0}]

**Comment by anurag-py** [comment]
This is the output that you are receiving the feed.  please provide whether there is any change in the code.
Please note that the code that i have sent subscribes to the continuous live market feed streaming of the request list.

**Comment by anurag-py** [comment]
the websocket streaming is working fine on my windows machine but not on the linux machine. perhaps the team can see if this is an os related issue.

Please refer to this issue https://github.com/MicrosoftDocs/azure-docs/issues/94331

**Comment by anurag-py** [comment]
to check the actual problem behind the same, i tweaked the connect method. The tweaked method is 

`def connect(self, wspayload: dict):
        try:
            self.web_url = f'wss://openfeed.5paisa.com/Feeds/api/chat?Value1={self.Jwt_token}|{self.client_code}'

            def on_open(ws):
                log_response("Streaming Started")
                try:
                    print(json.dumps(wspayload))
                    print("here")
                    ws.send(json.dumps(wspayload))
                except Exception as e:
                    log_response(e)

            def on_close(ws):
                log_response("Closed already")
            
            self.ws = websocket.WebSocketApp(self.web_url)
            import time
            for _ in range(100):
                if self.ws.sock and self.ws.sock.connected:
                    break
                time.sleep(0.1)
            self.ws.on_open = on_open(self.ws)
            
        except Exception as e:
            log_response(e)`

and the main code as:

`print(client.get_market_status())

def on_message(ws, message):
    print("hello")
    print(message)
    try:
        with open('mfspotdatabn21.txt', 'a+') as outfile:
            outfile.write(message)
            outfile.write('\n')
    except Exception as e:
        print(e)



req_list={ "Exch":"N","ExchType":"S","ScripCode":'999920005'}
            
print(type(req_list))
req_data=client.Request_Feed('i','s',req_list)
print(req_data)

client.connect(req_data)
client.receive_data(on_message)

print(client.Jwt_token)`


and i received the following output:

` 16:38:24 | Success
[{'Exch': 'N', 'ExchDescription': 'Nse Cash', 'ExchType': 'C', 'MarketStatus': 'Closed'}, {'Exch': 'N', 'ExchDescription': 'Nse Derivative', 'ExchType': 'D', 'MarketStatus': 'Closed'}, {'Exch': 'B', 'ExchDescription': 'Bse Cash', 'ExchType': 'C', 'MarketStatus': 'Closed'}, {'Exch': 'N', 'ExchDescription': 'Nse Currency', 'ExchType': 'U', 'MarketStatus': 'Open'}, {'Exch': 'B', 'ExchDescription': 'Bse Derivative', 'ExchType': 'D', 'MarketStatus': 'Closed'}, {'Exch': 'M', 'ExchDescription': 'MCX', 'ExchType': 'D', 'MarketStatus': 'Open'}]
<class 'dict'>
{'Method': 'Indices', 'Operation': 'Subscribe', 'ClientCode': '56628368', 'MarketFeedData': {'Exch': 'N', 'ExchType': 'S', 'ScripCode': '999920005'}}
 16:38:34 | Streaming Started
{"Method": "Indices", "Operation": "Subscribe", "ClientCode": "56628368", "MarketFeedData": {"Exch": "N", "ExchType": "S", "ScripCode": "999920005"}}
here
 16:38:34 | Connection is already closed.
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IjU2NjI4MzY4Iiwicm9sZSI6Ijc2NjMiLCJTdGF0ZSI6IiIsIlJlZGlyZWN0U2VydmVyIjoiQSIsIm5iZiI6MTY4NDQwNTQxNCwiZXhwIjoxNjg0NDM0NTk5LCJpYXQiOjE2ODQ0MDU0MTR9.RYD22PFpwbIuxRtvCl5gLWaRwfrNuMLQtQjPtqdG8g0
`

the websocket closes on itself.



I further tested the websocket using the chrome extension websocket test client and it worked fine on the linux machine.
![image](https://github.com/OpenApi-5p/py5paisa/assets/53002981/ca3bc857-5b53-4b15-89b9-fca0eeeb631e)

**Comment by anurag-py** [comment]
Hey!

Thanks for the help. I did try the solution as stated above before but the streaming contains all null values then.

I found a solution by using conda environment. It works like a charm in conda.

Moreover, the issue as far as i have identified is related to OPENSSL 3. Manjaro linux and even ubuntu updated to openssl 3. So instead of changing my system configuration i used conda environement as a workaround for now.

Anyways thanks for the help! Cheers

**Comment by SrikaraPranesh** [comment]
Hi @anurag-py can you provide a quick explanation on how you used Conda. Even I am facing same issue and it would help

**Comment by anurag-py** [comment]
@SrikaraPranesh Sorry for the delayed reply.

Simple steps are:
1. Install anaconda
2. Create and activate conda environment.
3.  Install py5paisa inside the environment.
4. And you are good to go.

The commands would be platform specific. I am working on linux. Let me know if you need any further help!

Thanks
