### ISSUE TITLE
client.get_totp_session returns error `Expecting value: line 1 column 1 (char 0)`

### ISSUE THREAD

**Issue by soumyajyotibiswas** [OpenApi-5p/py5paisa#296]
* 5paisa Python SDK version: py5paisa==0.7.12
* Python version: Python 3.12.3
* Operating System: Ubuntu 24.04 LTS

### Description

Describe what you were trying to get done.
I am trying to get the totp session, and I am hitting an error

Tell us what happened, what went wrong, and what you expected to happen.
using the 5paisa client, calling the `get_totp_session` with client_code, TOTP, and client pin, gives the error `Expecting value: line 1 column 1 (char 0)`

### What I Did

```
cred = {
            "APP_NAME": account_details["APP_NAME"],
            "APP_SOURCE": account_details["APP_SOURCE"],
            "USER_ID": account_details["USER_ID"],
            "PASSWORD": account_details["PASSWORD"],
            "USER_KEY": account_details["USER_KEY"],
            "ENCRYPTION_KEY": account_details["ENCRYPTION_KEY"],
        }
client = FivePaisaClient(cred=cred)
client.get_totp_session(client_code, TOTP, pin)
```

Error - `Expecting value: line 1 column 1 (char 0)`

This was working fine till the trading session ended 06/06/2024. Did something change in the backend?

**Comment by mtxeana** [comment]
Hi I am also getting the same error 

How did you resolve this ?
